### ISSUE TITLE
Enable diagnostic settings in Recovery Vault for Azure Site Recovery Diagnostics Events

### ISSUE THREAD

**Issue by ghostme** [Azure/CanadaPubSecALZ#105]
**Is your feature request related to a problem? Please describe.**
Create an azure policy to enable Azure Site Recovery diagnostic events to be sent to a log analytics workspace

**Describe the solution you'd like**
An Azure Policy is created to enable the following Site Recovery events to be  to a log analytics workspace

- AzureSiteRecoveryJobs
- AzureSiteRecoveryEvents
- AzureSiteRecoveryReplicatedItems
- AzureSiteRecoveryReplicationStats
- AzureSiteRecoveryRecoveryPoints
- AzureSiteRecoveryReplicationDataUploadRate
- AzureSiteRecoveryProtectedDiskDataChurn

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by SenthuranSivananthan** [comment]
We have the built-in policy assigned via LogAnalytics Policy Set (https://github.com/Azure/CanadaPubSecALZ/blob/main/policy/custom/definitions/policyset/LogAnalytics.bicep#L297).

The new policy would incorporate Backup & Site Recovery log events and replace the built-in policy in the policy set.
