### ISSUE TITLE
Least Priviledge for Pipelines - add the option to use a Service Principal for each

### ISSUE THREAD

**Issue by Adeelku** [Azure/CanadaPubSecALZ#113]
Add the option to : 

- use a Service Principal for each Pipeline 
- or use a master SP (as Currently configured)

Solution:

- breakdown the Azure Built-in Roles needed for each Pipeline
- provide the option to use a different SP for each pipeline with the appropriate RBAC role
- Maintain the option to use a master SP for all the pipelines

**Comment by skeeler** [comment]
Some implementation notes/thoughts to consider:
- retain backward compatibility with existing configuration structure (single SPN)
- for new (multiple value) SPNs, use object notation in the variable YAML file (inline)
