### ISSUE TITLE
Script the creation of the Pipelines in AzDo

### ISSUE THREAD

**Issue by Adeelku** [Azure/CanadaPubSecALZ#114]
Provide a script for the creation of the Pipelines in Azure DevOps

The solution will provide an option for automatd provisionning of the pipelines

**Comment by skeeler** [comment]
@Adeelku I have a collection of scripts that create pipelines, manage service principals & service endpoints, handle management groups, etc. - all items related to ADO setup (scripts the items mentioned in onboarding). Would you like me to take this issue for implementation or do you already have it done?

**Comment by Adeelku** [comment]
@skeeler , If you already have the scripts, please do - as I was planning to create them | Cheers

**Comment by skeeler** [comment]
This enhancement is addressed by #150
