### ISSUE TITLE
App service in ML landing zone should have private endpoint enabled for inbound

### ISSUE THREAD

**Issue by hudua** [Azure/CanadaPubSecALZ#131]
**Is your feature request related to a problem? Please describe.**
App service in ML landing zone should have private endpoint enabled for inbound

**Describe the solution you'd like**
App service linux container in the ML landing zone should have inbound private endpoint enabled

**Describe alternatives you've considered**
It is best to have private endpoint for inbound to align with the rest of the ML landing zone services

**Additional context**
No additional context needed!

**Comment by SenthuranSivananthan** [comment]
Reference:  https://docs.microsoft.com/en-us/azure/app-service/networking/private-endpoint

**Comment by SenthuranSivananthan** [comment]
We should enhance the existing implementation with 2 scenarios:

- private endpoint:
  - no extra subnet
  - no need for vnet integration

- public endpoint
  - extra subnet for subnet delegation
  - vnet integration for egress to vnet
