### ISSUE TITLE
A value for the 'policyAssignmentManagementGroupScope' parameter must be provided.

### ISSUE THREAD

**Issue by KingBain** [Azure/CanadaPubSecALZ#154]
Just updated to release seven. Updated the policy.yml file to latest.

Now receiving message when running pipeline 

![image](https://user-images.githubusercontent.com/367922/152428299-66c97238-4b62-438c-aa9d-73699b16017e.png)

can confirm the variable is set in the correct file 
![image](https://user-images.githubusercontent.com/367922/152433250-7a93f12f-a150-4b28-968b-c12759a8f0be.png)

![image](https://user-images.githubusercontent.com/367922/152433432-9ddd991c-2168-47b2-bd0a-6a1caee7fed0.png)

**Comment by SenthuranSivananthan** [comment]
Can you share the content on `templates/steps/assign-policy.yml` ?

**Comment by SenthuranSivananthan** [comment]
Update:  Troubleshooted with @KingBain and there was a missed merge for Custom Policy assignment step where this parameter is also required.  John, let me know once you've tested the pipeline run.

**Comment by KingBain** [comment]
not able to run the pipeline yet, but I swear the merge only caught the one line 

the two assigning spots
![image](https://user-images.githubusercontent.com/367922/152546995-dea0d1d3-a463-4c01-8734-a62248cb9d85.png)

![image](https://user-images.githubusercontent.com/367922/152547149-763d30a5-bb19-45cf-9665-84ae961820c9.png)

**Comment by KingBain** [comment]
adding those two lines resolves the issue.
