### ISSUE TITLE
Linter:  no-loc-expr-outside-params - ensure compliance

### ISSUE THREAD

**Issue by SenthuranSivananthan** [Azure/CanadaPubSecALZ#166]
**Is your feature request related to a problem? Please describe.**
As of Bicep version `v0.4.1272`, a new linter rule has been added to verify `resourceGroup().location` and `deployment().location` should only be used as the default value of a parameter.

We use `resourceGroup().location` throughout the project and should be replaced with a parameter (with default value to `resourceGroup().location`) so that the linter can be turned on with `error` level.

Reference:  https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/linter-rule-no-loc-expr-outside-params

Example warning:  https://github.com/Azure/CanadaPubSecALZ/runs/5170447255?check_suite_focus=true#step:5:106

```bash
az bicep build -f ./landingzones/lz-platform-logging/main.bicep 
WARNING: /home/runner/work/CanadaPubSecALZ/CanadaPubSecALZ/landingzones/lz-platform-logging/main.bicep(197,13) : Warning no-loc-expr-outside-params: Use a parameter here instead of 'deployment().location'. 'resourceGroup().location' and 'deployment().location' should only be used as a default value for parameters. [https://aka.ms/bicep/linter/no-loc-expr-outside-params]
```

**Comment by KingBain** [comment]
lol, ran into this this morning. Glad im not the only one :)

didnt stop the subscription pipeline...only through a warning

**Comment by SenthuranSivananthan** [comment]
I have a draft ready and working through testing to make sure there aren't any breaking changes.  This PR will be backward compatible when complete.

See:  https://github.com/SenthuranSivananthan/CanadaPubSecALZ/tree/linterLoc
