### ISSUE TITLE
Job DeployManagementGroupsJob: Environment main could not be found

### ISSUE THREAD

**Issue by autocloudarc** [Azure/CanadaPubSecALZ#173]
When running the management-groups-ci, this error appears (see image). Following instructions from reference: [CanadaPubSecALZ/azure-devops-pipelines.md at main · Azure/CanadaPubSecALZ · GitHub] https://github.com/Azure/CanadaPubSecALZ/blob/main/docs/onboarding/azure-devops-pipelines.md) Step 3.3: Configure Azure DevOps Pipeline. ![management-group-ci](https://user-images.githubusercontent.com/15109536/155047083-6167aff7-bde3-4a47-931b-a7a1ff0a8705.jpg)

**Comment by autocloudarc** [comment]
Discovered a functional workaround as follows:
1. Manually created a new environment named: dev
2. in the ...\config\variables\common.yml file, added the following entry at the top of the variables list (line 12): environment: dev
3. In the .../pipelines/management-groups.yml file, configured the jobs: environment property to reference the new common variable created in 2. above: environment: ${{ variables['environment'] }}

NOTE: I'm not sure if this is the best approach that is acceptable, but I am now able to run the pipeline job without issues and the management group structure was properly created this time :

![add-environment-to-common-variables](https://user-images.githubusercontent.com/15109536/155051827-d7388922-477f-4632-b49f-ec5d707f6f42.jpg)

**Comment by SenthuranSivananthan** [comment]
Thanks for raising this @autocloudarc.  This is because you will have to define an environment in Azure DevOps under Pipelines -> Environments.  This name should match that of the branch.  In the past, this was auto created by ADO when missing and looks like it is no longer.

I'll get the doc updated to reference the environment setting.

**Comment by SenthuranSivananthan** [comment]
@autocloudarc - Feel free to checkout the PR with the instructions:  https://github.com/Azure/CanadaPubSecALZ/pull/175/files

**Comment by skeeler** [comment]
Reopening to associate an additional code change to the onboarding scripts so that the `create-pipelines.bat` script automatically detects when the environment (named after the branch) does not already exist and automatically creates it.
