### ISSUE TITLE
The management group 'pubsecPlatformManagement' cannot be found.

### ISSUE THREAD

**Issue by autocloudarc** [Azure/CanadaPubSecALZ#176]
**Describe the bug**
Pipelline execution failure for pipeline: platform-logging-ci

**To Reproduce**
1. Configure the pipeline using instructions provided at: https://github.com/Azure/CanadaPubSecALZ/blob/main/docs/onboarding/azure-devops-pipelines.md Step 5 - Configure logging
2. Run the pipeline
3. See error: "The management group 'pubsecPlatformManagement' cannot be found."

**Expected behavior**
The logging subscription successfully deployed to the <prefix>PlatformManagement management group with the logging resources.

**Screenshots**
![theMGpubsecPlatformManagaementCannotBeFound](https://user-images.githubusercontent.com/15109536/155327592-f3cdf376-05ba-44ac-a687-4a190019c1ee.jpg)

**Additional context**
1. It appears that the management group name from the command pasted below still uses the hard-coded prefix 'pubsec', but I was using a different prefix previously (pfx01) when deploying the management group hierarchy, which was successful.
 2. The instructions didn't ask me to update the subscription ids and seems to have been using the previously hard-coded values.
 3. The full error message from the pipeline job raw logs is pasted below:

2022-02-23T12:35:44.4764180Z ##[error]Caller: 8 /home/vsts/work/_temp/azureclitaskscript1645619737000.sh, LineNo: 1, Command: az deployment mg create --location canadacentral --management-group-id pubsecPlatformManagement --template-file move-subscription.bicep --name ${deployName} --parameters managementGroupId='pubsecPlatformManagement' subscriptionId='redacted'

**Comment by autocloudarc** [comment]
Apologies CanadaPubSecALZ team! It seems that I just had to update all the other relevant variables in the **./config/variables/<devops-org-name>-<branch-name>.yml** file to include the following:

var-topLevelManagemetnGroupName: pfx01
var-logging-subscriptionId: 'redacted'
var-logging-logAnalyticsResourceGroupname: pfx01-central-logging-rg

This was an oversight on my part, but it would be great to explicitly specify these variables in the instructions as well. 

Here is the screenshot now with all the proper values, which worked like a charm for me now. Thanks again team. 

![logging-variables](https://user-images.githubusercontent.com/15109536/155330691-7c2f7653-7986-49c4-a69a-472f51875aa7.jpg)

Feel free to offer any additional guidance for this and close this issue when ready. Amazing work everyone! Thank you. 👍

**Comment by SenthuranSivananthan** [comment]
Glad you got it working.  We'll update the onboarding guide to call out these parameters.
