### ISSUE TITLE
Add subscription name parameter to JSON

### ISSUE THREAD

**Issue by KingBain** [Azure/CanadaPubSecALZ#179]
would this be possible, it seems like a fairly simple request. 

Add a value in the subscription json config files to represent the desired name of the subscription.

Thats way after the subscription has been moved out of the sandbox, that the subscription be named appropriately via the pipeline.

**Comment by SenthuranSivananthan** [comment]
Looks like [we should be able to rename the subscription](https://docs.microsoft.com/en-us/azure/templates/microsoft.management/managementgroups/subscriptions?tabs=bicep) based on an input.  Typically this would've happened when a subscription is created but I can see value in providing this as an optional parameter to configure.


```
resource symbolicname 'Microsoft.Management/managementGroups/subscriptions@2021-04-01' = {
  name: 'string'
  parent: resourceSymbolicName
}
```

**Comment by KingBain** [comment]
I was thinking more of a downstream validation and remediation event happening. 

validating subscription names, roles, alerts, etc

**Comment by SenthuranSivananthan** [comment]
I don't understand the use case that you are intending this being used for.

**Comment by SenthuranSivananthan** [comment]
I went through a few scenarios and it's not possible to rename a subscription with Bicep.

My original thought of using [this](https://docs.microsoft.com/en-us/azure/templates/microsoft.management/managementgroups/subscriptions?tabs=bicep) doesn't work.  It is used for moving a subscription to a management group.

I also tried using [Subscription Aliases](https://docs.microsoft.com/en-us/azure/templates/microsoft.subscription/aliases?tabs=bicep) but it can only be used when a new subscription is being created.

Therefore, the only options are:

* REST API - https://docs.microsoft.com/en-us/rest/api/subscription/2020-09-01/subscription/rename
* Azure CLI - https://docs.microsoft.com/en-us/cli/azure/account/subscription?view=azure-cli-latest#az-account-subscription-rename

My recommendation is to have the subscription named when it is created (either through Azure Portal or through ARM/Bicep)

**Comment by SenthuranSivananthan** [comment]
Closing this issue as we won't be able to modify subscription names using Bicep once they are created.  The options would be REST APIs, Az CLI and PowerShell.
