### ISSUE TITLE
RoleAssginmentUpdateNotPermitted during policy-ci pipeline run

### ISSUE THREAD

**Issue by autocloudarc** [Azure/CanadaPubSecALZ#181]
**Describe the bug**
Tenant ID, application ID, principal ID, and scope are not allowed to be updated.

**To Reproduce**
1. Run the roles-ci pipeline, Custom Policy Job, until the Assign Policy - Tags.bicep step.
2. See error below:

Deploying Tags.bicep using create operation at pfx02 scope ...

ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"RoleAssignmentUpdateNotPermitted\",\r\n    \"message\": \"Tenant ID, application ID, principal ID, and scope are not allowed to be updated.\"\r\n  }\r\n}"}]}}
##[error]Caller: 22 /home/vsts/work/_temp/azureclitaskscript1645736113481.sh, LineNo: 1, Command: az deployment mg create --location canadacentral --management-group-id pfx02 --template-file Tags.bicep --parameters Tags.populated.parameters.json
##[error]Script failed with exit code: 1
/usr/bin/az account clear
Finishing: Assign Policy Set - Tags.bicep

**Expected behavior**
All **Custom Policy Job** steps complete without errors.

**Screenshots**
![AssignPolicySet-Tags](https://user-images.githubusercontent.com/15109536/155616493-55e9abf9-df94-43c8-aab8-7621c28e8995.jpg)

**Additional context**
Add any other context about the problem here

**Comment by SenthuranSivananthan** [comment]
Looks like you might have a stale role assigned at the `pfx02` management group scope.

This error can happen if you deleted a policy assignment where the related role assignments (used for remediation) are not cleaned up afterwards.  See **Step 4** at https://github.com/Azure/CanadaPubSecALZ/blob/main/docs/policy/authoring-guide.md#remove-custom-policy-set-definition-and-assignment

Please check the Access Control for any role assignments that is set to "Unknown".  If you find any, please remove those stale role assignments and re-run the pipeline.

**Comment by autocloudarc** [comment]
Hi @SenthuranSivananthan. I didn't notice any stale role assignments so far, but I've already started cleaning up these deployments, and to start with a clean slate for my next practice iteration. l'll just pay close attention next time to see if this happens again and close this one for now.
