### ISSUE TITLE
Enable Azure AD authentication only for SQL Managed Instance (SQL MI)

### ISSUE THREAD

**Issue by mosharafMS** [Azure/CanadaPubSecALZ#196]
Problem:
Currently SQL MI requires SQL Login with password which is a security shortage to depend on a password every time provision SQL MI.  

Solution:
Supporting Azure AD authentication only for SQL MI so no need for a sql login with password to manage
Since it's now supported, it's better to have it enabled as option for the provisioning.

**Comment by SenthuranSivananthan** [comment]
Removed v0.11.0 milestone.  We will revisit based on demand.
