### ISSUE TITLE
Environment Configuration for Policy Selection

### ISSUE THREAD

**Issue by ccmsft** [Azure/CanadaPubSecALZ#198]
**Is your feature request related to a problem? Please describe.**
The default policies are hard-coded in the policy pipeline, but there are cases where a deployment might only require a subset of the builtin/custom policies.

**Describe the solution you'd like**
A configuration section for the selected policies within the environment configuration YAML.

**Describe alternatives you've considered**
1. Modifying the policy pipeline.
2. Manually deleting undesired policies after deployment.

**Comment by SenthuranSivananthan** [comment]
I think the best approach at the moment is to document the steps for editing the Policy pipeline.  This gives the flexibility to change, policy set assignments & scopes.
