### ISSUE TITLE
Allow for CanNotDelete lock on Resources to be configurable.

### ISSUE THREAD

**Issue by CalvinRodo** [Azure/CanadaPubSecALZ#204]
**Is your feature request related to a problem? Please describe.**
Yes we accidentally ran a ARM script in Complete mode and it deleted our log analytics workspace. To mitigate this issue we put a CanNotDelete lock on the workspace through infra as code.

**Describe the solution you'd like**
I would like to be able to prevent deletion of resources through the landing zone so we don't have to do it ourselves, as this feels like a feature that should be part of this landing zone.

**Describe alternatives you've considered**
Doing it ourselves.

**Comment by SenthuranSivananthan** [comment]
@CalvinRodo, we will put this into March release and make this delete lock turned on by default for the log analytics resource group.

**Comment by SenthuranSivananthan** [comment]
I hope you were able to restore the workspace using https://docs.microsoft.com/en-us/azure/azure-monitor/logs/delete-workspace

**Comment by CalvinRodo** [comment]
> I hope you were able to restore the workspace using https://docs.microsoft.com/en-us/azure/azure-monitor/logs/delete-workspace

Yeah we recovered no problem, we then put locks on but figured it might make more sense to have this be a part of the LZ so no one else makes the same mistake we did.

**Comment by SenthuranSivananthan** [comment]
Glad you are back online.  The PR is ready and will be merged today.  Thanks for bringing this up.
