### ISSUE TITLE
Instructions on how to verify proper subscription configuration and deployment 

### ISSUE THREAD

**Issue by KingBain** [Azure/CanadaPubSecALZ#209]
Would appreciate if there was a document that visually explained how/where to verify that subscription configurations have been properly deployed. 

Although the [subscription config files](https://github.com/Azure/CanadaPubSecALZ/blob/main/config/subscriptions/CanadaESLZ-main/pubsec/LandingZones/DevTest/4f9f8765-911a-4a6d-af60-4bc0473268c0_generic-subscription_canadacentral.json) are fair readable, they translate poorly when someone wants to validate that the subscription has been properly deployed and configured to the correct level via the pipeline.

Could a reference guide be created ?

| JSON | Portal |
|--|--|
|![image](https://user-images.githubusercontent.com/367922/157102575-7859db89-8f69-4f4c-a470-d5f87bfb26a2.png)|![image](https://user-images.githubusercontent.com/367922/157102933-c76c9205-a867-4912-a946-afd5042b6088.png)|

**Comment by SenthuranSivananthan** [comment]
Removing v0.11.0 milestone since we want to re-organize the documentation and validation steps.  We'll account for this feedback as part of the documentation workstream.

**Comment by Edybee** [comment]
By visually do you mean text (written) or video?
