### ISSUE TITLE
Documentation Enhancement

### ISSUE THREAD

**Issue by ghostme** [Azure/CanadaPubSecALZ#225]
1. Clarify the future usage of the EAN subnet in the Fortigate Hub virtual network
2. Add a note in the documentation that mentions that the NSGs deployed in the spokes are "generic" and these can be further customized to limit subnet-to-subnet traffic
3. Clarify if the Gateway subnet is meant to be an RFC 6598 address space
4. Add a note on the rationale for why each spoke subnet has its UDR, and not one UDR that is associated with multiple subnets
5. Add a note on how to modify the virtual appliance IP in the generic subscription template
6. Update UDR documentation for Appgw (PazSubnetUdr). UDR Next Hop for 0.0.0.0./0 should point to type "internet" and not the Azure Fw/Fortigate IP. This currently will affect the deployment and functionality of Application Gateway V2 as documented here. https://docs.microsoft.com/en-us/azure/application-gateway/configuration-infrastructure#supported-user-defined-routes

**Comment by SenthuranSivananthan** [comment]
Closed via #267
