### ISSUE TITLE
PrivateDNSZones - Parameter for CosmosDB not working

### ISSUE THREAD

**Issue by CldEng-DT** [Azure/CanadaPubSecALZ#227]
We have deployed the policy set/initiative for the DNSPrivateEndpoints and it's been working fine so far with the resource types used.  Some colleagues recently added private endpoints for CosmosDB and we noticed that the policy was not firing to automatically create the entry in the privatelink DNS zone.

After validating that the policy was properly deployed and a bit of looking in the Msft documentation, seems that the NameSpace used in the parameter file is targeting **Microsoft.CosmosDB/databaseAccounts**. (https://github.com/Azure/CanadaPubSecALZ/blob/main/policy/custom/definitions/policyset/DNSPrivateEndpoints.parameters.json) 

Looking at the built in policy to configure Cosmos DB with private endpoints, this policy targets **Microsoft.DocumentDB/databaseAccounts** instead.  After changing the namespace in the parameter file, the policy detected the private endpoints as non-compliant(which it did not do before) and executed the DeployIfNotExist privatelink entry.

**Comment by SenthuranSivananthan** [comment]
Thank you for raising this issue.
