### ISSUE TITLE
Document service health alert level information

### ISSUE THREAD

**Issue by skeeler** [Azure/CanadaPubSecALZ#308]
The sample environment configurations show `Incident` and `Security` service health alert levels being used, but there are others available. Document all available service health alert levels in a suitable project doc file (perhaps architecture.md), using the information at the following link: [Details on service health level information](https://docs.microsoft.com/en-us/azure/service-health/service-health-notifications-properties#details-on-service-health-level-information).

**Comment by SenthuranSivananthan** [comment]
We can create a section in each archetype doc for service health.  i.e. https://github.com/Azure/CanadaPubSecALZ/blob/main/docs/archetypes/generic-subscription.md#azure-deployment

Suggested text:

### Service Health

[Service health notifications](https://docs.microsoft.com/azure/service-health/service-health-notifications-properties) are published by Azure, and contain information about the resources under your subscription.  Service health notifications can be informational or actionable, depending on the category.

Our examples configure service health alerts for `Security` and `Incident`.  However, these categories can be customized based on your need.  Please review the possible options in [Azure Docs](https://docs.microsoft.com/azure/service-health/service-health-notifications-properties#details-on-service-health-level-information).

**Comment by skeeler** [comment]
@SenthuranSivananthan the above looks good.
