### ISSUE TITLE
Start date of budgets cannot be updated. Please delete and create a new budget.

### ISSUE THREAD

**Issue by KingBain** [Azure/CanadaPubSecALZ#317]
Was updating a subscription json file, adding a new role to a subscription. 

when the pipeline ran the job failed with error message 

"Start date of budgets cannot be updated. Please delete and create a new budget."

Havent seen this error before and google search shows, one return result about 7 days old. 

Maybe this is a new issue ? 

https://github.com/Azure/bicep/issues/7149

Full disclosure, we're running an old version of CALZ.

**Comment by skeeler** [comment]
@KingBain this is a limitation of the underlying API (https://docs.microsoft.com/rest/api/consumption/budgets/create-or-update) inability to update the `startDate` for an existing budget.
