### ISSUE TITLE
Private endpoint network security group support

### ISSUE THREAD

**Issue by SenthuranSivananthan** [Azure/CanadaPubSecALZ#332]
**Is your feature request related to a problem? Please describe.**
Private endpoint network security group support is now [generally available.](https://azure.microsoft.com/en-us/updates/general-availability-of-private-endpoint-network-security-group-support/)  We need to enable an NSG on the private endpoint subnet so that ACL's can be used to filter inbound traffic.

**Describe the solution you'd like**
Needs to be enabled on the **Machine Learning** and **Healthcare** archetypes

**Comment by skeeler** [comment]
The "generally available" link in issue description (above) is invalid (HTTP 404 Not Found).

The correct link is: https://azure.microsoft.com/updates/general-availability-of-network-security-groups-support-for-private-endpoints
