### ISSUE TITLE
Machine Learning archetype deployments failing (x4)

### ISSUE THREAD

**Issue by skeeler** [Azure/CanadaPubSecALZ#382]
The four CanadaPubSecALZ machine learning archetype (subscription) deployments are failing.

[Latest Azure DevOps pipeline run with errors](https://dev.azure.com/CanadaPubSecALZ/CanadaPubSecALZ/_build/results?buildId=25&view=results)

Related failures and initial attempts at correcting documented in Issue #380 

![image](https://github.com/Azure/CanadaPubSecALZ/assets/755941/dab5ef67-a19d-4929-a998-0ea86c41690b)

**Comment by skeeler** [comment]
@hudua can you assist with this issue?

**Comment by hudua** [comment]
Happy to help. I will look into this. Please note due to upcoming holidays and summer time, my resolution may be delayed.

**Comment by skeeler** [comment]
@hudua, can you look into this? Thanks!

**Comment by skeeler** [comment]
@hudua

**Comment by skeeler** [comment]
@hudua , can you look into this?
