### ISSUE TITLE
GitHub Actions with RunWorkflows.ps1 does not work after Az module new version release

### ISSUE THREAD

**Issue by aporodnov** [Azure/CanadaPubSecALZ#392]
**Describe the bug**
The PowerShell script fails when trying to execute #required line in RunWorkflows.ps1 or EnvironmentContext.ps1 after the recent Az module update.

**To Reproduce**
Steps to reproduce the behavior: Run any GitHub action for Azure deployment

**Additional context**
After the AZ Module update, we found that we need to remove:
1. The line "#Requires -Modules Az, powershell-yaml" from RunWorkflows.ps1
2. The line "#Requires -Modules powershell-yaml" from EnvironmentContext.ps1

**Comment by skeeler** [comment]
The "#Requires" lines from these scripts as well should be removed or commented out:

- scripts/configuration/Get-AlzConfiguration.ps1
- scripts/configuration/New-AlzCredential.ps1
- scripts/configuration/Remove-AlzCredential.ps1
- scripts/configuration/New-AlzDeployment.ps1
- scripts/configuration/New-AlzConfiguration.ps1
- scripts/configuration/Test-AlzCredential.ps1
