### ISSUE TITLE
Support for AKS w/ Azure CNI

### ISSUE THREAD

**Issue by Adeelku** [Azure/CanadaPubSecALZ#48]
Adding code to support Azure CNI network plugin for the AKS module

https://docs.microsoft.com/en-us/azure/aks/concepts-network

Azure CNI, provides the following capabilities (compared to Kubenet):

•	Network policy (Azure) is native – Calico can be used as an add-on at Cluster creation
•	Support for Windows Nodes
•	Support for Virtual nodes
•	Allows connecting to existing Azure | on-premises resources directly via IP addresses assigned to each pod

However, Azure CNI requires pre-designing and creating a VNET in advance as well as more IPs (than Kubenet) 

Adding the option to use either:

- _Network Plugin: Kubenet or Azure CNI
- _Network Policy_: for Kubenet: Calico | for Azure CNI: azure (Azure Network Policy) or Calico
- https://docs.microsoft.com/en-us/azure/aks/use-network-policies

**Comment by SenthuranSivananthan** [comment]
@Adeelku I'm removing this issue from v0.5.0.  We need to have the scope defined before assigning to milestone.
