### ISSUE TITLE
unrecognized template parameter 'logAnalyticsRetentionInDays'.

### ISSUE THREAD

**Issue by KingBain** [Azure/CanadaPubSecALZ#50]
logAnalyticsRetentionInDays needs to be removed from the example ADO document 

its not supported AND not used in the two other example files 
![image](https://user-images.githubusercontent.com/367922/140249777-b03331e2-96bf-47a4-b153-72e7b66b711b.png)

**Comment by KingBain** [comment]
hmm, nevermind. still getting the eror message 

```
Current working directory: /home/vsts/work/1/s/landingzones/lz-platform-logging

Deploying main.bicep using create operation...
ERROR: unrecognized template parameter 'logAnalyticsRetentionInDays'. Allowed parameters: logAnalyticsAutomationAccountName, logAnalyticsResourceGroupName, logAnalyticsWorkspaceName, resourceTags, securityCenter, serviceHealthAlerts, subscriptionBudget, subscriptionRoleAssignments, subscriptionTags
##[error]Caller: 5 /home/vsts/work/_temp/azureclitaskscript1635994635337.sh, LineNo: 1, Command: az deployment sub create --location canadacentral --subscription 88358fdf-3ca9-4b73-b561-38f4934ab400 --template-file main.bicep --parameters serviceHealthAlerts='{
    "resourceGroup
```

**Comment by KingBain** [comment]
![image](https://user-images.githubusercontent.com/367922/140251307-d7fdf334-7d86-456c-abec-91972ee570c0.png)

removing theline from the template, seems to have resolved the issue

**Comment by KingBain** [comment]
Looks like issue is related to #44

**Comment by SenthuranSivananthan** [comment]
@KingBain can you check if you have the latest code?  We added this parameter in #44 and it's reflected in  https://github.com/Azure/CanadaPubSecALZ/blob/main/landingzones/lz-platform-logging/main.bicep#L185

**Comment by KingBain** [comment]
updating the source code resolved the issue thanks.
