### ISSUE TITLE
Rename config/variables to config/environments

### ISSUE THREAD

**Issue by skeeler** [Azure/CanadaPubSecALZ#67]
As stated in title, make it clearer that the YAML variable files are organized by (deployment) environments.

**Comment by SenthuranSivananthan** [comment]
As part of this config reorganization, wondering whether the subscription configuration should also be moved under environment?

i.e.

```
config
  |- environments
     |- CanadaESLZ-main.yml
     |- common.yml
     |- subscriptions
         |- rest of the directory structure we already have in place

```

**Comment by skeeler** [comment]
As discussed with @SenthuranSivananthan, closing this issue/enhancement as it's not clear that renaming the folder adds sufficient value relative to effort.
