### ISSUE TITLE
Support Azure AD only authentication in Synapse SQL Pools

### ISSUE THREAD

**Issue by mosharafMS** [Azure/CanadaPubSecALZ#69]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

**Describe the solution you'd like**
[Configure and manage Azure AD authentication with Azure SQL](https://docs.microsoft.com/en-us/azure/azure-sql/database/authentication-aad-configure?tabs=azure-powershell#azure-ad-authentication-methods)

**Comment by SenthuranSivananthan** [comment]
@mosharafMS Should we target this update for December?

**Comment by mosharafMS** [comment]
AzureADOnlyAuth Not supported in canadacentral. 
@SenthuranSivananthan please mark it blocked for now.

**Comment by SenthuranSivananthan** [comment]
This feature is now available in Canada Central.
