### ISSUE TITLE
Support Container Instance as a deployment target for AML

### ISSUE THREAD

**Issue by mosharafMS** [Azure/CanadaPubSecALZ#70]
**Is your feature request related to a problem? Please describe.**
AKS deployment and maintenance is quite complicated compared to Azure Container Instances 

**Describe the solution you'd like**
Support Azure Container Instance as a deployment target for AML in the ML landing zone

**Comment by SenthuranSivananthan** [comment]
@hudua - We've chatted about supporting App Service in the past as the model runtime for AML.  How feasible is ACI in the ML archetype?

**Comment by hudua** [comment]
Yes, ACI is a good idea for the ML archetype. For Azure Container Instance, the preferred route would be deploy to virtual network: https://docs.microsoft.com/en-us/azure/container-instances/container-instances-vnet. Since deployment of ACI requires an image and image source, I would suggest we address this issue as an integration test scenario. Thought?

**Comment by hudua** [comment]
Please stay tuned...

**Comment by hudua** [comment]
I'm working on integration test scripts and automation scripts for ML archetype to enable deployment to app service (instead of container instance). There is a well-known limitation that container instance cannot pull from container registry with private endpoint.

**Comment by SenthuranSivananthan** [comment]
We would need to get this limitation lifted before integration.  Do you want to open a technical feedback for ACI engineering to address?

**Comment by hudua** [comment]
Microsoft internal ticket submitted for this feedback. Focus for now will be to deploy model to App service

**Comment by hudua** [comment]
d

**Comment by hudua** [comment]
Edited - re-opened due to accidental user error...

**Comment by hudua** [comment]
Will close this issue for now. ACI now supports ACR with private endpoint using managed identity, but this doesn't work for ACI inside vnet so not fully supported for the ML landing zone.

[Deploy container image from Azure Container Registry using a managed identity - Azure Container Instances | Microsoft Docs](https://docs.microsoft.com/en-us/azure/container-instances/using-azure-container-registry-mi)

![image](https://user-images.githubusercontent.com/40040433/166299007-abfc4fdc-c3b7-4505-97a7-642a3de5c35b.png)
