### ISSUE TITLE
Create data analytics LZ

### ISSUE THREAD

**Issue by mosharafMS** [Azure/CanadaPubSecALZ#71]
**Is your feature request related to a problem? Please describe.**
Although most products needed for the Analytics landing zone are available, there's no Analytics landing zone 

**Describe the solution you'd like**
Create a new landing zone for data analytics

**Comment by SenthuranSivananthan** [comment]
@mosharafMS Do you have a specific architecture or design in mind?  

@hudua Can you connect with Mohammad to see what's missing from the ML Landing Zone.  I think we should be able to extend the design to incorporate new components & capabilities.

**Comment by hudua** [comment]
@SenthuranSivananthan for sure!

@mosharafMS good call. We have most services for enabling data analytics but have a few current gaps for a Data Analytics Landing Zone, including Azure Purview. If you have an initial design / architecture that would be great. But yes let's connect on this

**Comment by mosharafMS** [comment]
@SenthuranSivananthan & @hudua  I think the best way to go forward with diversify landing zones is to make all the resources optional through the enabled field just like the sqldb.enabled which allows the users to turn on or off the sqldb. If we add this to all the resources then the master landing zone will have all the resources and it's up to users who wants to customize to turn on and off. For example if we take the machine learning lz and removed AKS, ACR and added Synapse, that's a good start for Analytics lz 

What do you think?

**Comment by SenthuranSivananthan** [comment]
I like this approach.  It will allow for customizing the deployment without creating many different archetypes.

**Comment by Adeelku** [comment]
I would suggest that we add the option to automate the creation and configuration of ADF's SHIR VM as well

**Comment by mboswell** [comment]
@SenthuranSivananthan  - how does this align to the global work on Data Management and Analytics Scenarion (ESA) which was published to CAF in August? Is there an ability to put some industry focus on and above the scenario we've been working on? Trying to stop multiple forks and multiple conversations which confuse the customer. 

Please reach out to @abdale if there is a chance to build on top.

**Comment by SenthuranSivananthan** [comment]
@mboswell , there's always a chance to build on top and leverage the good work from you and the team w/ Data Management & Analytics scenario.

@mosharafMS and @hudua, let's connect with @abdale and see whether we can leverage what's published and share feedback we are hearing from projects.

**Comment by hudua** [comment]
Absolutely, this is very top of mind for us, in building on top of the global Data Management & Analytics, while ensuring we align with Canadian federal gov patterns and requirements (the industry flavour). Connecting offline now in discussions.

Further comments and ideas always welcome!!

**Comment by mosharafMS** [comment]
![image](https://user-images.githubusercontent.com/23546820/145461933-dcdd4c74-837d-4271-b2d5-8cc86db1e787.png)

This is a very common design and when we have all the services with enable/disable switch then customizing the landing zone would be very easy

**Comment by SunChero** [comment]
the fact that some tools doesnt offer much visibility or control over where the compute is happening. is in my opinion  one of the biggest challenges to run data analytics tools in a controlled/certified environment 
up until now .. i don't see a way to make synapse link or attach to an existing spark cluster!
so i believe when designing sush a zone .. we should pay more attention to that aspect

**Comment by mosharafMS** [comment]
The main issue is that not all services support enabled switch. Once we have it then creating a new landing zone will be a matter for parameters customization. Let's archive this issue for now and reopen it when we have all services ready @SenthuranSivananthan
