### ISSUE TITLE
Generate random names for Key vaults

### ISSUE THREAD

**Issue by mosharafMS** [Azure/CanadaPubSecALZ#72]
**Is your feature request related to a problem? Please describe.**
When testing the landing zone, it's inevitable the same deployment will be deployed multiple times. because keyvault is set with anti purging, there's no wait to create a vault with the same name as a deleted vault. 

**Describe the solution you'd like**
use date and time of the creation in the uniquestring function to generate a hash that is dependent on a variable not just a fixed value like the resource group id.

**Comment by SenthuranSivananthan** [comment]
For integration testing we already create random key vault names so they can be deleted without waiting for purge period to complete.  For actual use, it's best to leave it as-is and avoid deleting the AKV instances between tests.

**Comment by mosharafMS** [comment]
closing
