### ISSUE TITLE
No need to store sql connection string in AKV

### ISSUE THREAD

**Issue by mosharafMS** [Azure/CanadaPubSecALZ#73]
**Is your feature request related to a problem? Please describe.**
storing SQL DB connection string in key vault is unnecessary extra step that is not needed. The SQL user name and password are saved in AKV in the case of SQL authentication and in the case of AAD only authentication, there's no need to save anything. 

**Describe the solution you'd like**
Remove the module that stores the connection string in AKV

**Comment by SenthuranSivananthan** [comment]
I think it makes sense since the connection string doesn't specify any database at the time it's created either.  Can you please remove it from Machine Learning & Healthcare archetypes?
