### ISSUE TITLE
Toggle for required tags from enforcement to auditing.

### ISSUE THREAD

**Issue by CalvinRodo** [Azure/CanadaPubSecALZ#84]
**Is your feature request related to a problem? Please describe.**
We are unable to deploy resources from the portal due to the required tags having to exist for resources to be deployed, it also makes it difficult to follow some guides for deploying things like Sentinel Connectors.

**Describe the solution you'd like**
A variable that allows us to switch enforcement from deny deployments to audits. This way we can still require tags but don't have to block deployments through the portal. I like to manually configure some resources then sync them with Terraform after the fact since I'm not as comfortable with Azure as I am with other CSP's at the moment. 

**Describe alternatives you've considered**
I can remove the required tags but it's still nice to be able some enforcement in pace

**Comment by SenthuranSivananthan** [comment]
This is a good feedback.  We will look at providing audit & deny as options that you can configure for tags.

**Comment by CalvinRodo** [comment]
I copied changes from the PR into my repo and it worked like a treat!
