### ISSUE TITLE
GitHub Action for PR Check should only validate files that have changed.

### ISSUE THREAD

**Issue by CalvinRodo** [Azure/CanadaPubSecALZ#86]
Instead of validating all the files in the Bicep files in the repo it should only validate bicep scripts that have been modified since the last PR

This scan takes 6 minutes to run in a PR that has zero changes to bicep scripts, although this PR does add a variable that was missing. However based on the fact that my PR missing the required variable passed this check I'm assuming the template validation doesn't check for variables so I'm guessing it doesn't need to run unless files being validated are changed.

**Comment by SenthuranSivananthan** [comment]
We validate all Bicep files because it is the only way to know if any changes have cascading failures in the references.

Can you share your example where the PR check didn't work?

**Comment by CalvinRodo** [comment]
To Replicate what happened just remove the `var-logging-logAnalyticsRetentionInDays` variable from the configuration variables. 

I grabbed files from upstream and merged that in. 

The PR that I merged without the variable is here: 
https://github.com/cds-snc/CanadaPubSecALZ/pull/3

**Comment by SenthuranSivananthan** [comment]
I understand the scenario now.  We don't run the deployments during the PR check to validate if the inputs are validate.  This would increase the PR check time to multiple hours given some scenarios like SQL Managed Instances can take ~ 3 hours to provision.

In this case, the variable from the config file and not related to the Bicep templates themselves.

We are looking to move the configuration from YAML to JSON and add json schema validation.  This validation would catch these missing parameters.  This work is already complete for the archetypes like Generic Subscriptions, Machine Learning & Healthcare and it's checked in the PR validation step.

Our next focus area would be Logging & Networking but I don't have an ETA yet.
