### ISSUE TITLE
Azure Pipeline jobs don't run when config values are modified. 

### ISSUE THREAD

**Issue by CalvinRodo** [Azure/CanadaPubSecALZ#87]
Pipelines in Azure DevOps should run when changes to https://github.com/Azure/CanadaPubSecALZ/tree/main/config/ are merged to main.

**Comment by SenthuranSivananthan** [comment]
We don't run these by default to give customers the trigger the pipelines in a controlled fashion.  You can change the triggers in the pipeline yml as required.
