### ISSUE TITLE
Support Azure App Service as a deployment target for AML

### ISSUE THREAD

**Issue by SenthuranSivananthan** [Azure/CanadaPubSecALZ#93]
**Is your feature request related to a problem? Please describe.**
AKS deployment and maintenance is quite complicated compared to Azure App Service

**Describe the solution you'd like**
Support Azure App Service as a deployment target for AML in the ML landing zone

**Comment by SenthuranSivananthan** [comment]
Related to #70

**Comment by SenthuranSivananthan** [comment]
@mosharafMS - FYI - Given the blocker w/ ACI + Private ACR, App Service would be a good path forward as replacement for AKS.

**Comment by hudua** [comment]
In progress - should be coming out with a PR in the next few days

**Comment by SenthuranSivananthan** [comment]
@hudua Should we target December release for this?
