### ISSUE TITLE
Example region should probably be canadaeast

### ISSUE THREAD

**Issue by CalvinRodo** [Azure/CanadaPubSecALZ#94]
The example region specified is causing issues  https://github.com/Azure/CanadaPubSecALZ/blob/main/docs/onboarding/ado.md#step-31-update-commonyml-in-git-repository 

When I try to deploy the G-Suite Workplace connector to canadacentral it fails because the function (I'm guessing linux functions aren't available in the region) can't run there. 

Because i was unaware of that I have to either migrate our LogWorkspace to canadacentral or pay to egress data across regions.

Since functions is probably going to be a common pattern to ingest logs into sentinel the example should probably default to canadacentral.

**Comment by SenthuranSivananthan** [comment]
The example region in the config is Canada Central.

**Comment by SenthuranSivananthan** [comment]
@CalvinRodo for the G-Suite Workspace connector, can you open a GH Issue at https://github.com/Azure/Azure-Sentinel/issues so that the connector can be deployed to any region and doesn't have a hard dependency on "Consumption plan Linux"?
