### ISSUE TITLE
Unable to deploy hub managed private endpoint policy assignment

### ISSUE THREAD

**Issue by SenthuranSivananthan** [Azure/CanadaPubSecALZ#98]
Steps to reproduce:

1. Run either `platform-connectivity-hub-azfw-ci` or `platform-connectivity-hub-nva-ci` pipeline.

**Error:**

Hub Network will manage private dns zones, creating Azure Policy assignment to automatically create Private Endpoint DNS Zones
Deploying policy assignment using policy/custom/assignments/dns-private-endpoints.bicep
ERROR: An error occurred reading file. Could not find file '/home/vsts/work/1/s/policy/custom/assignments/dns-private-endpoints.bicep'.

##[error]Caller: 10 /home/vsts/work/_temp/azureclitaskscript1638139169085.sh, LineNo: 1, Command: az deployment mg create --location canadacentral --management-group-id pubsec --template-file dns-private-endpoints.bicep --parameters policyAssignmentManagementGroupId='pubsec' policyDefinitionManagementGroupId='pubsec' privateDNSZoneSubscriptionId='ed7f4eed-9010-4227-b115-2a5e37728f27' privateDNSZoneResourceGroupName='pubsec-dns-rg'
##[error]Script failed with exit code: 1

Related to #78

**Comment by Adeelku** [comment]
I believe policy-ci should be run agai  before the Hub pipelines

**Comment by SenthuranSivananthan** [comment]
@Adeelku - Yes, it does run, however network pipelines create the policy assignment based on `var-hubnetwork-deployPrivateDnsZones` in `CanadaESLZ-main.yml` (in our environment).

It's a regression after I renamed policy assignment file names.

**Comment by Adeelku** [comment]
okay ! theanks @SenthuranSivananthan
